/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComunidadesRouteImport } from './routes/comunidades'
import { Route as DuvidasRouteImport } from './routes/duvidas'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesRoute = ComunidadesRouteImport.update({
  id: '/comunidades',
  path: '/comunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const DuvidasRoute = DuvidasRouteImport.update({
  id: '/duvidas',
  path: '/duvidas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunidades': typeof ComunidadesRoute
  '/duvidas': typeof DuvidasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunidades': typeof ComunidadesRoute
  '/duvidas': typeof DuvidasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunidades': typeof ComunidadesRoute
  '/duvidas': typeof DuvidasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comunidades'
    | '/duvidas'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/servicos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comunidades'
    | '/duvidas'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/servicos/$slug'
  id:
    | '__root__'
    | '/'
    | '/comunidades'
    | '/duvidas'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/servicos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunidadesRoute: typeof ComunidadesRoute
  DuvidasRoute: typeof DuvidasRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades': {
      id: '/comunidades'
      path: '/comunidades'
      fullPath: '/comunidades'
      preLoaderRoute: typeof ComunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duvidas': {
      id: '/duvidas'
      path: '/duvidas'
      fullPath: '/duvidas'
      preLoaderRoute: typeof DuvidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunidadesRoute: ComunidadesRoute,
  DuvidasRoute: DuvidasRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ServicosSlugRoute: ServicosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
